# scalar types with type check
scalar Contact
scalar Email
scalar DateTime

# scalar types without type check
scalar Token
scalar Any


# input types
input Pagination {
	page: Int
	limit: Int
}

# enum types
enum SortOption {
	toLargest
	toSmallest
}

# types
type MutationResponse {
	status: Int!
	message: String!
	data: Any
}