type Query {
	users(
		userId: ID
		search: String
		sort: UserSort = {}
		pagination: Pagination = {}
	): [User!]!
}

type Mutation {
	login(
		username: String! 
		password: String!
	): AuthResponse!

	register(
		username: String! 
		password: String!
		contact: Contact!
		email: Email
	): AuthResponse!

	changeUser(
		username: String
		password: String
		contact: Contact
		email: Email
	): MutationResponse!
}

type User {
	userId: ID!
	username: String!
	contact: Contact!
	email: Email
	userCreatedAt: DateTime!
}

type AuthResponse {
	status: Int!
	message: String!
	token: Token
	user: User
}

input UserSort {
	userId: SortOption
	username: SortOption
}